version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/test-flow

    steps:
      - checkout

      - run: yarn
      - run: yarn start

      - setup_remote_docker

      - deploy:
          name: Build and push Docker image
          command: |
            docker build -t opuscapita/test-flow:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push opuscapita/test-flow:latest
