version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7-browsers
    working_directory: /test-flow

    steps:
      - checkout

      - run: yarn
      - run: export TESTING_URL=http://52.233.155.169 ; yarn start -- --testing_url=$TESTING_URL

      - setup_remote_docker

      - deploy:
          name: Build and push Docker image
          command: |
            docker build -t opuscapita/test-flow:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push opuscapita/test-flow:latest
